### ISSUE TITLE
error while installing

### ISSUE THREAD

**Issue by Rex-Diego** [yyr/ncl-mode#7]
I use spacemacs, and when I install ncl-mode with `M-x package-install RET ncl-mode RET` , it shows me the following message:
```
Compiling file /Users/rex/.emacs.d/elpa/ncl-mode-20160925.2200/company-ncl-mode.el at Tue Nov  8 10:18:49 2016
Entering directory ‘/Users/rex/.emacs.d/elpa/ncl-mode-20160925.2200/’
company-ncl-mode.el:25:1:Error: Cannot open load file: No such file or directory, company
```

Is something wrong with spacemacs's config? I'm using Emacs 25.1 (which installed by 
```
$ brew tap d12frosted/emacs-plus
$ brew install emacs-plus
$ brew linkapps emacs-plus
```
following the  [spacemacs's tutorial](https://github.com/syl20bnr/spacemacs#install).

**Comment by Rex-Diego** [comment]
I'm so stupid. Forget to see the error line, I didn't install company package. Now, it works.

Sorry for bothering you with my simple issue. Close it.Thanks!

**Comment by yyr** [comment]
Thanks for trying this package out.. I believe there are many rough edges. It works great for me.. But I feel casual emacs users may find it difficult to setup everything properly. 

Please try out all the features.. if some thing is broken let me know here.

Thank you.
