### ISSUE TITLE
How to make variable name auto-complete?

### ISSUE THREAD

**Issue by Rex-Diego** [yyr/ncl-mode#8]
This is a great mode! Thank you for your development!

But as a newbie to emacs I can not make the company-mode list the variable names in the current buffer.
The auto completion of internal ncl function names and resource names works well. After google it, I can only make hippie-expand to complete the variable name manually. But as imenu can list all the variables out, there must be a better way to do this: company-mode not only list the function names in the dict but also the variables in this buffer.

**Comment by yyr** [comment]
Thanks for trying out ncl-mode,

I think that can be done with adding a company-mode backend for var names. Currently  company support is very primitive, I will improve that and add that soon.

**Comment by Rex-Diego** [comment]
@yyr Thank you! Hoping for the next version!

**Comment by Rex-Diego** [comment]
@yyr Hello, finally I find a way to do what I want. But there is a little problem. 
I changed the ```ncl-mode-autoload.el```(line 15):
```(add-hook 'ncl-mode-hook (lambda nil (set (make-local-variable 'company-backends) '(company-ncl-mode))))```
into 
```(add-hook 'ncl-mode-hook (lambda nil (set (make-local-variable 'company-backends) '((company-files company-dabbrev company-gtags company-etags company-keywords company-ncl-mode )))))```
and the company will auto-complete the variable names and keywords in the comment part.

But I don't think I should make changes inside your package instead of customize my own init.el. The problem is if I add ```(add-hook 'ncl-mode-hook (lambda nil (set (make-local-variable 'company-backends) '((company-files company-dabbrev company-gtags company-etags company-keywords company-ncl-mode )))))``` in my init.el. It seems to be overwrite by the default one in the ```ncl-mode-autoload.el```

Any suggestions about making my favorite company-backends without changing the code in your packages?

**Comment by yyr** [comment]
may be using `(eval-after-load ...`
would do it I guess,

Anyway the solution suggested is very harmless, so I added in the package and pushed it in 84599a730169b9b19f9dcc532e20dcdc9648bbaa.

Please update and see if it works for you.

By the way, how do you install ncl-mode? (melpa, el-get, manual)

**Comment by Rex-Diego** [comment]
@yyr Thanks! I'll try it out and let you know what I'm seeing.

I'm using melpa, FYI.

**Comment by Rex-Diego** [comment]
@yyr BTW, I've tried ```(with-eval-after-load 'ncl-mode (add-hook 'ncl-mode-hook (lambda nil (set (make-local-variable 'company-backends) '((company-ncl-mode company-files company-dabbrev company-gtags company-etags company-keywords))))))```
and ```(eval-after-load 'ncl-mode (add-hook 'ncl-mode-hook (lambda nil (set (make-local-variable 'company-backends) '((company-ncl-mode company-files company-dabbrev company-gtags company-etags company-keywords))))))
``` in my init.el. The former does not make any difference and the later will make ncl-mode does not work anymore. 
But
 ```
(add-hook 'python-mode-hook
	  (lambda ()
	    (set (make-local-variable 'company-backends) '((company-anaconda company-dabbrev-code)
							   company-dabbrev)))
	  )
``` works when I prefer anaconda-mode than python-mode, so I thought there is some organization problem in the ncl-mode blocking customize user's config. (Sorry I did not figure out how anaconda-mode is organized, so I cannot give some valuable suggestions.)

And I tried your new commit 84599a7. It does not work either, but when the order of these backends are changed and ```company-ncl-mode```is the last one in the list everything will be fine. I don't know why company-ncl-mode will block other company backends when it is in the first position, this does not happen in the anaconda-mode either.

**Comment by yyr** [comment]
Hi thanks for testing out,
The last commit in ncl-mode was in such a way that there is no need to add anything to user init.el. 

company-backends trigger one at a time (unless they are clubbed together in a list). For every mode the major company backend has to come first in the list. if it comes in the last it mostly won't work.

you could check the value of company-backends while you are editing the particular mode. 
could you post  var value both in python-mode and ncl-mode buffers? (Use C-h v )

for example my python-mode has 

```
(company-jedi company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)
```
and ncl-mode has

```
((company-ncl-mode company-dabbrev company-etags company-gtags company-files))
```
and my company-mode seems to be working as it is supposed to be.

**Comment by Rex-Diego** [comment]
When I try to make a gif I find everything works now........😥😥
It's amazing and I don't know why. Maybe emacs recompiled the el files when I restart it. 

Thanks for helping me out.

**Comment by yyr** [comment]
Thanks for the feed back, glad that it works now. 

Please make any feature requests if needed. 

Closing the issue.
